#!/bin/bash

pushd `dirname $0` > /dev/null
SCRIPTPATH=`pwd -P`
popd > /dev/null
PROJECTPATH=$SCRIPTPATH/..

if [ ! -e $PROJECTPATH/venv/ ]; then
    python3 -m venv $PROJECTPATH/venv
fi

$PROJECTPATH/venv/bin/pip3 install -r $SCRIPTPATH/requirements.txt